apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
type: Opaque
stringData:
  JENKINS_ADMIN_ID: admin
  JENKINS_ADMIN_PASSWORD: admin123
  JENKINS_URL: http://jenkins.jenkins.svc.cluster.local:8080

