# k8s/secrets-admin.yaml
apiVersion: v1
kind: Secret
metadata:
 name: jenkins-admin-secret
 namespace: jenkins
stringData:
  JENKINS_ADMIN_ID: admin
  JENKINS_ADMIN_PASSWORD: admin1234
  JENKINS_URL: http://jenkins:8080
